version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
    networks:
      - ada-2-kotlin

  worker:
    build:
      context: .
    command: [ "worker" ]
    environment:
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - ada-2-kotlin

networks:
  ada-2-kotlin:
    name: ada-2-kotlin
